#! /bin/sh
### BEGIN INIT INFO
# Provides:          single
# Required-Start:    $local_fs $all killprocs
# Required-Stop:
# Default-Start:     1
# Default-Stop:
# Short-Description: executed by init(8) upon entering runlevel 1 (single).
### END INIT INFO

PATH=/sbin:/bin

. /lib/lsb/init-functions

do_start () {
	log_action_msg "Starting lcd service"
	exec /opt/node/bin/node /home/pi/src/lcd/app.js start
}

do_stop() {
	log_action_msg "Stopping lcd service"
	exec /opt/node/bin/node /home/pi/src/lcd/app.js stop
}

case "$1" in
  start)
	do_start
	;;
  restart|reload|force-reload)
	do_stop && do_start
	;;
  stop)
	do_stop
	;;
  *)
	echo "Usage: $0 start|stop" >&2
	exit 3
	;;
esac
